# Application
spring.application.name=billingApp

# Database
spring.datasource.url=jdbc:mysql://mysql:3306/billingdb
spring.datasource.username=billinguser
spring.datasource.password=billingpass
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.database-platform=org.hibernate.dialect.MySQL8Dialect
spring.jpa.hibernate.ddl-auto=update

# Kafka
spring.kafka.bootstrap-servers=kafka:29092
spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.springframework.kafka.support.serializer.JsonSerializer

# Kafka Topics
kafka.topic.payment=payment-topic
kafka.topic.prescription=prescription-topic

# Logging
logging.level.com.hospital.billing=DEBUG